### ISSUE TITLE
Feature Request: Radio Selector instead of Checkbox Selector

### ISSUE THREAD

**Issue by josesho** [plotly/dash-table-experiments#15]
Hi Chris and Dash team,

Just wondering if there are plans to create a radio-selector table (ie, only one row may be selected at any time) vs the current checkbox-style selection (multiple rows at any time if `selectable = True`. 

If not, I'm a little stumped in using callback logic to force the `selected_row_indices` property to 'pop' any selected rows and to only take on the last selected row value.

Appreciate any thoughts or help! Thanks.

**Comment by chriddyp** [comment]
This is a great idea. A couple folks brought this up in the community forum: https://community.plot.ly/t/dash-datatable-distinguishing-between-single-row-select-and-multi-row-select/6093/6, but let's track the issue here.

AFAIK, this isn't possible right now. I believe that the last item in the `selected_row_indices` (`selected_row_indices[-1]`) should be the last selected row, but I can't say for certain.

Here is the issue in the associated issue in the underlying data grid: https://github.com/adazzle/react-data-grid/issues/908

***

If any company out there would like to sponsor this feature, [please reach out](https://plot.ly/products/consulting-and-oem/)

**Comment by josesho** [comment]
Yes @chriddyp , In my own poking around, it is possible to grab the data from the last selected row easily (but using `selected_row_indices[0]` instead?). It seems like this is restricted by the underlying React table's defaults?

Thanks!
J.

**Comment by josesho** [comment]
conversely, is there a way to pull the rowdata simply by clicking of the row itself? (can't seem to find any docs in the react-data-grid to suggest that one could)

**Comment by Shimwell** [comment]
The check boxes are great and radio buttons sound like a nice addition. I guess it won't make any sense to include the check all option at the top of the column when working with radio buttons. Perhaps this could be a feature to show or hide the upper most checkbox / radio button

**Comment by doccray** [comment]
Hi All,
there is a workaround to implement single selections with the `row_selectable` feature.
This is not optimal because there is still the checkbox in the header row but maybe it is useful for somebody.

![peek 2018-05-01 16-06](https://user-images.githubusercontent.com/38048365/39484266-77f5133c-4d75-11e8-901e-409894c1291d.gif)

Here are the changes:
https://github.com/doccray/dash-table-experiments/commit/8e2bba57b17074f4ee08d1e27b30b798d9b72ca8

@chriddyp Is this worth a pull request?

**Comment by Shimwell** [comment]
That looks most useful to me 😀. I would like to use this feature on a dash webapp I am making. I create the experimental table dynamicaly and sometimes it can be large enough that the select all check box slows down the app. https://9md3uimove.execute-api.us-east-1.amazonaws.com/dev/mydash

**Comment by josesho** [comment]
Looks great! Upvote for PR!

**Comment by slash31** [comment]
Yes, PR, please. @chriddyp @doccray

**Comment by chriddyp** [comment]
> @chriddyp Is this worth a pull request?

Yup! I'm 👍 with those changes

**Comment by ndmurray** [comment]
This looks great, although I'm trying to implement by importing DataTable.react.js in addition to the original bundle.js file for dash_table_experiments to no avail. Do you have any advice on how to implement this new DataTable.react.js file?

**Comment by rquintino** [comment]
hi all? just to check any update on the feature or release? would be very useful
thx!

**Comment by rquintino** [comment]
just adding, wasn't clear if this will be possible with the PR, would be useful to separate current selection (checkboxed based) from current row clicked/highlighted (click on any cell in the row).

Main scenario is reacting every time I click anywhere on a row , ex: see detail layout on right. A scenario I use a lot in R shiny.
thx!

**Comment by heonjushin** [comment]
Is there any schedule to release this feature? I'm really looking forward to it :)

**Comment by ZsofiaHa3** [comment]
Any updates on this?

**Comment by alexcjohnson** [comment]
This package is obsolete and about to be archived. The current package [`dash-table`](https://github.com/plotly/dash-table) has this option, `row_selectable='single'` https://dash.plot.ly/datatable/interactivity
